<%--
  Created by IntelliJ IDEA.
  User: thearaseng
  Date: 4/1/20
  Time: 5:22 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Index page generated by Internal Resource View Resolver</title>
</head>
<body>
    <p>Index page generated by Internal Resource View Resolver</p>
</body>
</html>
