<%@ page language="java" contentType="text/xml;charset=UTF-8" pageEncoding="UTF-8" %><?xml version="1.0" encoding="UTF-8"?>
<RESPONSE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EnquiryRspV4.xsd">
    <SERVICE>ENQUIRYV4</SERVICE>
    <ACTION>A_SC</ACTION>
    <STATUS>OK</STATUS>
    <HEADER>
        <MEMBER_ID>63</MEMBER_ID>
        <USER_ID>PPC_XML</USER_ID>
        <RUN_NO>1</RUN_NO>
        <TOT_ITEMS>1</TOT_ITEMS>
    </HEADER>
    <MESSAGE>
        <ITEM>
            <ENQUIRY_REFERENCE>${referenceNo}</ENQUIRY_REFERENCE>
            <RSP_REPORT>
                <ENQUIRY_TYPE>NA</ENQUIRY_TYPE>
                <REPORT_DATE>02/04/2020</REPORT_DATE>
                <ENQUIRY_NO>349603286</ENQUIRY_NO>
                <PRODUCT_TYPE>PHL</PRODUCT_TYPE>
                <NO_OF_APPLICANTS>2</NO_OF_APPLICANTS>
                <ACCOUNT_TYPE>J</ACCOUNT_TYPE>
                <ENQUIRY_REFERENCE>${referenceNo}</ENQUIRY_REFERENCE>
                <AMOUNT>30000.00</AMOUNT>
                <CURRENCY>USD</CURRENCY>
                <CONSUMER>
                    <CAPL>P</CAPL>
                    <CID>
                        <CID1>N</CID1>
                        <CID2 lang="kh">170723617</CID2>
                        <CID3>14/02/2023</CID3>
                    </CID>
                    <PROVIDED>
                        <PCNAM>
                            <PCNMFE>SUY</PCNMFE>
                            <PCNM1E>ODAMANY</PCNM1E>
                        </PCNAM>
                        <PCDOB>01/05/1979</PCDOB>
                        <PCPLB>
                            <PCPLBC>KHM</PCPLBC>
                            <PCPLBP>12</PCPLBP>
                        </PCPLB>
                        <PCGND>M</PCGND>
                        <PCMAR>U</PCMAR>
                        <PCNAT>KHM</PCNAT>
                    </PROVIDED>
                    <ADDITIONAL_NAMES>
                        <ADDITIONAL_NAME>
                            <ANM_CNMFE>SUY</ANM_CNMFE>
                            <ANM_CNM1E>ODAMANY</ANM_CNM1E>
                            <ANM_LOAD_DT>02/04/2020</ANM_LOAD_DT>
                        </ADDITIONAL_NAME>
                    </ADDITIONAL_NAMES>
                    <ADDRESSES>
                        <ADDRESS>
                            <CA_LOAD_DT>02/04/2020</CA_LOAD_DT>
                            <CA_CADT>RESID</CA_CADT>
                            <CA_PROV>02</CA_PROV>
                            <CA_DIST>0204</CA_DIST>
                            <CA_COMM>020401</CA_COMM>
                            <CA_VILL>02040105</CA_VILL>
                            <CA_CAD9>KHM</CA_CAD9>
                        </ADDRESS>
                    </ADDRESSES>
                    <EMPLOYERS>
                        <EMPLOYER>
                            <EDLD>02/04/2020</EDLD>
                            <ETYP>C</ETYP>
                            <ESLF>N</ESLF>
                            <EOCE><![CDATA[ACCOUNTING& OTHER FINANCIAL CONSULTATION]]></EOCE>
                            <ELEN>27</ELEN>
                            <ETMS>600.00</ETMS>
                            <ECURR>USD</ECURR>
                            <ENME>SUY ODAMANY</ENME>
                            <EADR>
                                <EA_CADT>RESID</EA_CADT>
                                <EA_PROV>02</EA_PROV>
                                <EA_DIST>0208</EA_DIST>
                                <EA_COMM>020809</EA_COMM>
                                <EA_VILL>02080901</EA_VILL>
                                <EA_AD9>KHM</EA_AD9>
                            </EADR>
                        </EMPLOYER>
                    </EMPLOYERS>
                    <ADVISORY_SUMMARY_TEXT>
                        <ADVISORY_TEXT>NOADV</ADVISORY_TEXT>
                    </ADVISORY_SUMMARY_TEXT>
                    <SUMMARY>
                        <CNT_PE>0</CNT_PE>
                        <CNT_MTDE>0</CNT_MTDE>
                        <CNT_ACC>0</CNT_ACC>
                        <CNT_ACC_NORM>0</CNT_ACC_NORM>
                        <CNT_ACC_DELQ>0</CNT_ACC_DELQ>
                        <CNT_ACC_CLO>0</CNT_ACC_CLO>
                        <CNT_ACC_REJ>0</CNT_ACC_REJ>
                        <CNT_ACC_WRO>0</CNT_ACC_WRO>
                        <CNT_GACC>0</CNT_GACC>
                        <CNT_GACC_NORM>0</CNT_GACC_NORM>
                        <CNT_GACC_DELQ>0</CNT_GACC_DELQ>
                        <CNT_GACC_ACC_CLO>0</CNT_GACC_ACC_CLO>
                        <CNT_GACC_REJ>0</CNT_GACC_REJ>
                        <CNT_GACC_WRO>0</CNT_GACC_WRO>
                        <TOT_LIMITS>
                            <TOT_LIM>0.00</TOT_LIM>
                        </TOT_LIMITS>
                        <TOT_GLIMITS>
                            <TOT_GLIM>0.00</TOT_GLIM>
                        </TOT_GLIMITS>
                        <TOT_LIABILITIES>
                            <TOT_LIAB>0.00</TOT_LIAB>
                        </TOT_LIABILITIES>
                        <TOT_GLIABILITIES>
                            <TOT_GLIAB>0.00</TOT_GLIAB>
                        </TOT_GLIABILITIES>
                        <TOT_WO_AMT>
                            <TOT_WO>0.00</TOT_WO>
                        </TOT_WO_AMT>
                        <TOT_GWO_AMT>
                            <TOT_GWO>0.00</TOT_GWO>
                        </TOT_GWO_AMT>
                        <TOT_WO_OS_BALANCE>
                            <TOT_WO_OS_BAL>0.00</TOT_WO_OS_BAL>
                        </TOT_WO_OS_BALANCE>
                        <TOT_GWO_OS_BALANCE>
                            <TOT_GWO_OS_BAL>0.00</TOT_GWO_OS_BAL>
                        </TOT_GWO_OS_BALANCE>
                    </SUMMARY>
                    <SCORE>
                        <SC_ERROR>Applicant has no information on bureau</SC_ERROR>
                    </SCORE>
                </CONSUMER>
                <CONSUMER>
                    <CAPL>P</CAPL>
                    <CID>
                        <CID1>N</CID1>
                        <CID2 lang="kh">120018156</CID2>
                        <CID3>17/08/2025</CID3>
                    </CID>
                    <PROVIDED>
                        <PCNAM>
                            <PCNMFE>RUN</PCNMFE>
                            <PCNM1E>PUTHEAVY</PCNM1E>
                        </PCNAM>
                        <PCDOB>28/06/1985</PCDOB>
                        <PCPLB>
                            <PCPLBC>KHM</PCPLBC>
                            <PCPLBP>12</PCPLBP>
                        </PCPLB>
                        <PCGND>F</PCGND>
                        <PCMAR>U</PCMAR>
                        <PCNAT>KHM</PCNAT>
                    </PROVIDED>
                    <AVAILABLE>
                        <ACID>
                            <ACID1>N</ACID1>
                            <ACID2 lang="kh">120018156</ACID2>
                        </ACID>
                        <ACNAM>
                            <ACNMFA lang="kh">រុន</ACNMFA>
                            <ACNM1A lang="kh">ពុទ្ថាវី</ACNM1A>
                            <ACNMFE>RUN</ACNMFE>
                            <ACNM1E>PUTHEAVY</ACNM1E>
                        </ACNAM>
                        <ACDOB>25/06/1985</ACDOB>
                        <ACPLB>
                            <ACPLBC>KHM</ACPLBC>
                            <ACPLBP>07</ACPLBP>
                            <ACPLBD>0706</ACPLBD>
                        </ACPLB>
                        <ACGND>F</ACGND>
                        <ACMAR>W</ACMAR>
                        <ACNAT>KHM</ACNAT>
                    </AVAILABLE>
                    <ADDITIONAL_NAMES>
                        <ADDITIONAL_NAME>
                            <ANM_CNMFA lang="kh">រុន</ANM_CNMFA>
                            <ANM_CNM1A lang="kh">ពុទ្ថាវី</ANM_CNM1A>
                            <ANM_LOAD_DT>20/01/2015</ANM_LOAD_DT>
                        </ADDITIONAL_NAME>
                        <ADDITIONAL_NAME>
                            <ANM_CNMFA lang="kh">រុន</ANM_CNMFA>
                            <ANM_CNM1A lang="kh">ពុទ្ធាវី</ANM_CNM1A>
                            <ANM_LOAD_DT>18/10/2012</ANM_LOAD_DT>
                        </ADDITIONAL_NAME>
                    </ADDITIONAL_NAMES>
                    <PREV_ENQUIRIES>
                        <PREV_ENQUIRY>
                            <PE_DATE>20/01/2015</PE_DATE>
                            <PE_ENQR>ACLEDA BANK PLC</PE_ENQR>
                            <PE_TYPE>NA</PE_TYPE>
                            <PE_ACCT>S</PE_ACCT>
                            <PE_MEMB_REF>KPT-KEP 966355</PE_MEMB_REF>
                            <PE_PRD>WCL</PE_PRD>
                            <PE_AMOUNT>3500.00</PE_AMOUNT>
                            <PE_CURR>USD</PE_CURR>
                            <PE_APPL>P</PE_APPL>
                            <PE_NAME>
                                <PE_NMFA lang="kh">រុន</PE_NMFA>
                                <PE_NM1A lang="kh">ពុទ្ថាវី</PE_NM1A>
                                <PE_NMFE>run</PE_NMFE>
                                <PE_NM1E>putheavy</PE_NM1E>
                            </PE_NAME>
                        </PREV_ENQUIRY>
                        <PREV_ENQUIRY>
                            <PE_DATE>18/10/2012</PE_DATE>
                            <PE_ENQR>ACLEDA BANK PLC</PE_ENQR>
                            <PE_TYPE>NA</PE_TYPE>
                            <PE_ACCT>S</PE_ACCT>
                            <PE_MEMB_REF>KPT-KEP-966355</PE_MEMB_REF>
                            <PE_PRD>SME</PE_PRD>
                            <PE_AMOUNT>2500.00</PE_AMOUNT>
                            <PE_CURR>USD</PE_CURR>
                            <PE_APPL>P</PE_APPL>
                            <PE_NAME>
                                <PE_NMFA lang="kh">រុន</PE_NMFA>
                                <PE_NM1A lang="kh">ពុទ្ធាវី</PE_NM1A>
                                <PE_NMFE>RUN</PE_NMFE>
                                <PE_NM1E>PUTHEAVY</PE_NM1E>
                            </PE_NAME>
                        </PREV_ENQUIRY>
                    </PREV_ENQUIRIES>
                    <ACC_DETAILS>
                        <ACC_DETAIL>
                            <ACC_CRDTR>ACLEDA BANK PLC</ACC_CRDTR>
                            <ACC_PRD>WCL</ACC_PRD>
                            <ACC_ACC_NO>0700LD1116000017</ACC_ACC_NO>
                            <ACC_RST_LOAN>N</ACC_RST_LOAN>
                            <ACC_CURR>KHR</ACC_CURR>
                            <ACC_LIMIT>7000000.00</ACC_LIMIT>
                            <ACC_ISSU_DT>09/06/2011</ACC_ISSU_DT>
                            <ACC_PROD_EXP_DT>18/10/2012</ACC_PROD_EXP_DT>
                            <ACC_STATUS>C</ACC_STATUS>
                            <ACC_CLSD_DT>26/11/2012</ACC_CLSD_DT>
                            <ACC_TNR>16</ACC_TNR>
                            <ACC_FRQ>M</ACC_FRQ>
                            <ACC_INSTL>781000.00</ACC_INSTL>
                            <ACC_SEC>TO</ACC_SEC>
                            <ACC_CUB>0.00</ACC_CUB>
                            <ACC_ODB>0.00</ACC_ODB>
                            <ACC_LAST_AMT_PD>781000.00</ACC_LAST_AMT_PD>
                            <ACC_LAST_PAY_DT>18/10/2012</ACC_LAST_PAY_DT>
                            <ACC_AS_OF_DT>21/11/2012</ACC_AS_OF_DT>
                            <ACC_SUMMRY>C000M00000000MMMMM</ACC_SUMMRY>
                            <ACC_CAPL>P</ACC_CAPL>
                        </ACC_DETAIL>
                        <ACC_DETAIL>
                            <ACC_CRDTR>ACLEDA BANK PLC</ACC_CRDTR>
                            <ACC_PRD>WCL</ACC_PRD>
                            <ACC_ACC_NO>0700LD1229300018</ACC_ACC_NO>
                            <ACC_RST_LOAN>N</ACC_RST_LOAN>
                            <ACC_CURR>USD</ACC_CURR>
                            <ACC_LIMIT>2500.00</ACC_LIMIT>
                            <ACC_ISSU_DT>19/10/2012</ACC_ISSU_DT>
                            <ACC_PROD_EXP_DT>17/10/2014</ACC_PROD_EXP_DT>
                            <ACC_STATUS>C</ACC_STATUS>
                            <ACC_CLSD_DT>17/10/2014</ACC_CLSD_DT>
                            <ACC_TNR>24</ACC_TNR>
                            <ACC_FRQ>M</ACC_FRQ>
                            <ACC_INSTL>105.96</ACC_INSTL>
                            <ACC_SEC>TO</ACC_SEC>
                            <ACC_CUB>0.00</ACC_CUB>
                            <ACC_ODB>0.00</ACC_ODB>
                            <ACC_LAST_AMT_PD>105.96</ACC_LAST_AMT_PD>
                            <ACC_LAST_PAY_DT>17/10/2014</ACC_LAST_PAY_DT>
                            <ACC_AS_OF_DT>03/11/2014</ACC_AS_OF_DT>
                            <ACC_SUMMRY>C00000000000000000000000</ACC_SUMMRY>
                            <ACC_CAPL>P</ACC_CAPL>
                        </ACC_DETAIL>
                        <ACC_DETAIL>
                            <ACC_CRDTR>ACLEDA BANK PLC</ACC_CRDTR>
                            <ACC_PRD>WCL</ACC_PRD>
                            <ACC_ACC_NO>3803LD1502100805</ACC_ACC_NO>
                            <ACC_RST_LOAN>N</ACC_RST_LOAN>
                            <ACC_CURR>USD</ACC_CURR>
                            <ACC_LIMIT>3500.00</ACC_LIMIT>
                            <ACC_ISSU_DT>21/01/2015</ACC_ISSU_DT>
                            <ACC_PROD_EXP_DT>16/01/2017</ACC_PROD_EXP_DT>
                            <ACC_STATUS>C</ACC_STATUS>
                            <ACC_CLSD_DT>16/01/2017</ACC_CLSD_DT>
                            <ACC_TNR>24</ACC_TNR>
                            <ACC_FRQ>M</ACC_FRQ>
                            <ACC_INSTL>148.62</ACC_INSTL>
                            <ACC_SEC>TO</ACC_SEC>
                            <ACC_CUB>0.00</ACC_CUB>
                            <ACC_ODB>0.00</ACC_ODB>
                            <ACC_LAST_AMT_PD>148.62</ACC_LAST_AMT_PD>
                            <ACC_LAST_PAY_DT>16/01/2017</ACC_LAST_PAY_DT>
                            <ACC_AS_OF_DT>31/01/2017</ACC_AS_OF_DT>
                            <ACC_SUMMRY>C00000000000000000000000</ACC_SUMMRY>
                            <ACC_CAPL>P</ACC_CAPL>
                        </ACC_DETAIL>
                    </ACC_DETAILS>
                    <ADDRESSES>
                        <ADDRESS>
                            <CA_LOAD_DT>09/10/2016</CA_LOAD_DT>
                            <CA_CADT>RESID</CA_CADT>
                            <CA_PROV>23</CA_PROV>
                            <CA_DIST>2301</CA_DIST>
                            <CA_COMM>230103</CA_COMM>
                            <CA_VILL>23010302</CA_VILL>
                            <CA_CAD9>KHM</CA_CAD9>
                        </ADDRESS>
                        <ADDRESS>
                            <CA_LOAD_DT>05/03/2015</CA_LOAD_DT>
                            <CA_CADT>RESID</CA_CADT>
                            <CA_CAD1A lang="kh">ព្រៃតាកុយ ពងទឹក ដំណាក់ចង្អើរ</CA_CAD1A>
                            <CA_CAD9>KHM</CA_CAD9>
                        </ADDRESS>
                        <ADDRESS>
                            <CA_LOAD_DT>20/01/2015</CA_LOAD_DT>
                            <CA_CADT>RESID</CA_CADT>
                            <CA_PROV>23</CA_PROV>
                            <CA_CAD1E>KEP</CA_CAD1E>
                            <CA_CAD8E>23</CA_CAD8E>
                            <CA_CAD9>KHM</CA_CAD9>
                        </ADDRESS>
                    </ADDRESSES>
                    <EMPLOYERS>
                        <EMPLOYER>
                            <EDLD>02/04/2020</EDLD>
                            <ETYP>C</ETYP>
                            <ESLF>N</ESLF>
                            <EOCE>OTHER PROFESSION(SPECIALIZED JOB)</EOCE>
                            <ELEN>25</ELEN>
                            <ETMS>600.00</ETMS>
                            <ECURR>USD</ECURR>
                            <ENME>RUN PUTHEAVY</ENME>
                            <EADR>
                                <EA_CADT>RESID</EA_CADT>
                                <EA_PROV>02</EA_PROV>
                                <EA_DIST>0203</EA_DIST>
                                <EA_COMM>020310</EA_COMM>
                                <EA_VILL>02031004</EA_VILL>
                                <EA_AD9>KHM</EA_AD9>
                            </EADR>
                        </EMPLOYER>
                        <EMPLOYER>
                            <EDLD>20/01/2015</EDLD>
                            <ETYP>C</ETYP>
                            <ESLF>Y</ESLF>
                            <EOCE>OWNER</EOCE>
                            <ELEN>99</ELEN>
                            <ETMS>2000.00</ETMS>
                            <ECURR>USD</ECURR>
                            <ENME>OWNER</ENME>
                            <EADR>
                                <EA_CADT>RESID</EA_CADT>
                                <EA_PROV>23</EA_PROV>
                                <EA_AD1E>KEP</EA_AD1E>
                                <EA_AD8E>23</EA_AD8E>
                                <EA_AD9>KHM</EA_AD9>
                            </EADR>
                        </EMPLOYER>
                        <EMPLOYER>
                            <EDLD>18/10/2012</EDLD>
                            <ETYP>C</ETYP>
                            <ESLF>Y</ESLF>
                            <EOCE>OWNER</EOCE>
                            <ELEN>90</ELEN>
                            <ETMS>3250.00</ETMS>
                            <ECURR>USD</ECURR>
                            <ENME>OWNER</ENME>
                            <EADR>
                                <EA_CADT>RESID</EA_CADT>
                                <EA_PROV>23</EA_PROV>
                                <EA_DIST>2301</EA_DIST>
                                <EA_AD1E>KEP</EA_AD1E>
                                <EA_AD8E>23</EA_AD8E>
                                <EA_AD9>KHM</EA_AD9>
                            </EADR>
                        </EMPLOYER>
                    </EMPLOYERS>
                    <ADVISORY_SUMMARY_TEXT>
                        <ADVISORY_TEXT>NOADV</ADVISORY_TEXT>
                    </ADVISORY_SUMMARY_TEXT>
                    <SUMMARY>
                        <CNT_PE>2</CNT_PE>
                        <CNT_MTDE>0</CNT_MTDE>
                        <CNT_ACC>3</CNT_ACC>
                        <CNT_ACC_NORM>0</CNT_ACC_NORM>
                        <CNT_ACC_DELQ>0</CNT_ACC_DELQ>
                        <CNT_ACC_CLO>3</CNT_ACC_CLO>
                        <CNT_ACC_REJ>0</CNT_ACC_REJ>
                        <CNT_ACC_WRO>0</CNT_ACC_WRO>
                        <CNT_GACC>0</CNT_GACC>
                        <CNT_GACC_NORM>0</CNT_GACC_NORM>
                        <CNT_GACC_DELQ>0</CNT_GACC_DELQ>
                        <CNT_GACC_ACC_CLO>0</CNT_GACC_ACC_CLO>
                        <CNT_GACC_REJ>0</CNT_GACC_REJ>
                        <CNT_GACC_WRO>0</CNT_GACC_WRO>
                        <EISDT>09/06/2011</EISDT>
                        <TOT_LIMITS>
                            <TOT_LIM_CURR>KHR</TOT_LIM_CURR>
                            <TOT_LIM>7000000.00</TOT_LIM>
                        </TOT_LIMITS>
                        <TOT_LIMITS>
                            <TOT_LIM_CURR>USD</TOT_LIM_CURR>
                            <TOT_LIM>6000.00</TOT_LIM>
                        </TOT_LIMITS>
                        <TOT_GLIMITS>
                            <TOT_GLIM>0.00</TOT_GLIM>
                        </TOT_GLIMITS>
                        <TOT_LIABILITIES>
                            <TOT_LIAB_CURR>KHR</TOT_LIAB_CURR>
                            <TOT_LIAB>0.00</TOT_LIAB>
                        </TOT_LIABILITIES>
                        <TOT_LIABILITIES>
                            <TOT_LIAB_CURR>USD</TOT_LIAB_CURR>
                            <TOT_LIAB>0.00</TOT_LIAB>
                        </TOT_LIABILITIES>
                        <TOT_GLIABILITIES>
                            <TOT_GLIAB>0.00</TOT_GLIAB>
                        </TOT_GLIABILITIES>
                        <TOT_WO_AMT>
                            <TOT_WO>0.00</TOT_WO>
                        </TOT_WO_AMT>
                        <TOT_GWO_AMT>
                            <TOT_GWO>0.00</TOT_GWO>
                        </TOT_GWO_AMT>
                        <TOT_WO_OS_BALANCE>
                            <TOT_WO_OS_BAL>0.00</TOT_WO_OS_BAL>
                        </TOT_WO_OS_BALANCE>
                        <TOT_GWO_OS_BALANCE>
                            <TOT_GWO_OS_BAL>0.00</TOT_GWO_OS_BAL>
                        </TOT_GWO_OS_BALANCE>
                    </SUMMARY>
                    <SCORE>
                        <SC_SCORE>950</SC_SCORE>
                        <SC_SCORECARD>BNK01</SC_SCORECARD>
                        <SC_SCOREINDEX>4</SC_SCOREINDEX>
                        <SC_ODDS>181</SC_ODDS>
                        <SC_BAD>0.54</SC_BAD>
                        <SC_MINIMUM>-200</SC_MINIMUM>
                        <SC_MAXIMUM>1200</SC_MAXIMUM>
                    </SCORE>
                </CONSUMER>
                <DISCLAIMER>
                    <DI_TEXT>This information has been collated from various sources. It does not represent the opinion
                        of Credit Bureau Cambodia and Credit Bureau Cambodia assumes no responsibility for it. Credit
                        Bureau Cambodia will not be liable (in contract or otherwise whatsoever) with respect to the
                        collation or supply of the information or any use made of it, whether in relation to its
                        accuracy or completeness or any other matter whatsoever. The information is supplied on a
                        confidential basis to you and not for the use or reliance of any other party except any person
                        on whose behalf you have sought the information.
                    </DI_TEXT>
                </DISCLAIMER>
            </RSP_REPORT>
        </ITEM>
    </MESSAGE>
</RESPONSE>